version: "2"

services:
  # uncomment to setup nginx proxy
  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro

  quito.core:
    image: progsmart/quito.core:latest
    restart: unless-stopped
    volumes:
      - ./quito.data/blobstorage:/data/blobstorage
      - ./quito.data/filestorage:/data/filestorage
    ports:
      - "8080:8080"
    # uncomment if nginx proxy is in use
    depends_on: 
    #  - nginx-proxy
      - app
    env_file:
      - ./env/quito.env

  db:
    build: db
    read_only: true
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./env/db.env

  app:
    build:
      context: app
      # uncomment following lines for team edition or change UID/GID
      args:
          - edition=team
      #   - PUID=1000
      #   - PGID=1000
    restart: unless-stopped
    # uncomment if nginx proxy is in use
    # depends_on: 
    #   - nginx-proxy
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - ./volumes/app/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./env/app.env

  web:
    build: web
    ports:
      - "80:80"
      - "443:443"
    read_only: true
    restart: unless-stopped
    volumes:
      # This directory must have cert files if you want to enable SSL
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./env/web.env
