#!/home/phillipj/Desktop/Calico/Quito/Quito-Core/src/quito.core/bin/python2.7

import sys
from robot import rebot_cli

# Multiprocessing guard
# https://github.com/robotframework/robotframework/issues/2315
if __name__ == '__main__':
    rebot_cli(sys.argv[1:])
